version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cat-api-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: cat-api
    volumes:
      - mongodb_data:/data/db
    networks:
      - cat-api-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: cat-api-backend
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongodb:27017/cat-api
      NODE_ENV: production
      CAT_API_KEY: ${CAT_API_KEY}
      CAT_API_URL: https://api.thecatapi.com/v1
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cat-api-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  cat-api-network:
    driver: bridge
